"""Saved-fold identity, train-only preprocessing, feature exclusion and reproducibility."""

from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import pytest
import yaml
from sklearn.pipeline import Pipeline

from eris_ml.evaluation import model_comparison as comparison
from eris_ml.evaluation.feature_ablation import GROUPS, REMOVED
from eris_ml.evaluation.model_comparison_reporting import build_report
from eris_ml.features.definitions import load_feature_definition
from eris_ml.models.factory import create_estimator

ROOT = Path(__file__).resolve().parents[2]
DEFINITIONS = {name: load_feature_definition(ROOT / f"configs/features/feature_set_{name}.yaml")
               for name in REMOVED}
CONFIGS = {name: yaml.safe_load((ROOT / f"configs/models/{name}.yaml").read_text())
           for name in comparison.TREE_MODELS}


def fixture() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    rng = np.random.default_rng(24)
    frame = pd.DataFrame({name: rng.uniform(1, 50, 60)
                          for kind in ("numeric", "ordinal") for name in GROUPS[kind]})
    for name in GROUPS["nominal"]:
        frame[name] = [f"{name}-{i}" for i in range(60)]
    frame.loc[0, "Age"] = np.nan
    frame["source_row"] = np.arange(100, 160)
    frame["EmployeeNumber"] = np.arange(1000, 1060)
    frame["Attrition"] = np.tile([0, 0, 1], 20)
    assignment = frame[comparison.IDS[:3]].copy()
    # Intentionally not generated by StratifiedKFold; must be consumed unchanged.
    assignment["fold"] = np.repeat([3, 1, 5, 2, 4], 12)
    assignment["development_position"] = np.arange(60)
    tables = []
    for name in REMOVED:
        for model in ("dummy_prior", "logistic_regression"):
            table = assignment[comparison.IDS].copy()
            table["feature_set"], table["model"] = name, model
            table["probability"] = rng.uniform(0.05, 0.95, 60)
            tables.append(table)
    return frame, assignment, pd.concat(tables, ignore_index=True)


def test_isolation_projection_reproducibility_and_reference(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    data, assignment, baseline = fixture()
    original_data, original_baseline = data.copy(deep=True), baseline.copy(deep=True)
    original_fit, original_predict = Pipeline.fit, Pipeline.predict_proba
    fitted: list[Pipeline] = []
    expected_validation: dict[int, list[int]] = {}

    def small_estimator(config: dict[str, Any]) -> Any:
        # Real RF/XGB implementations, reduced size only in synthetic tests.
        return create_estimator(config).set_params(n_estimators=3, n_jobs=1)

    def fit(self: Pipeline, features: pd.DataFrame, target: Any, **kwargs: Any) -> Any:
        if "model" not in self.named_steps:
            return original_fit(self, features, target, **kwargs)
        position = len(fitted) % 40
        name, fold = list(REMOVED)[position // 10], position % 5 + 1
        train = np.flatnonzero(assignment.fold.to_numpy() != fold)
        assert list(features.columns) == list(DEFINITIONS[name].all_features)
        assert not (set(features.columns) & REMOVED[name])
        assert features.index.tolist() == train.tolist()
        assert np.array_equal(target, data.Attrition.to_numpy()[train])
        assert all(self is not previous for previous in fitted)
        fitted.append(self)
        expected_validation[id(self)] = np.flatnonzero(assignment.fold.to_numpy() == fold).tolist()
        value = original_fit(self, features, target, **kwargs)
        preprocessor = self.named_steps["preprocessor"]
        encoder = preprocessor.named_transformers_["nominal"].named_steps["encoder"]
        for column, categories in zip(DEFINITIONS[name].nominal, encoder.categories_, strict=True):
            assert set(categories) == set(features[column].dropna())
        for kind in ("numeric", "ordinal"):
            columns = list(getattr(DEFINITIONS[name], kind))
            learned = preprocessor.named_transformers_[kind].named_steps
            medians = features[columns].median()
            assert np.allclose(learned["imputer"].statistics_, medians)
            assert np.allclose(learned["scaler"].mean_, features[columns].fillna(medians).mean())
        return value

    def predict(self: Pipeline, features: pd.DataFrame, **kwargs: Any) -> Any:
        assert features.index.tolist() == expected_validation[id(self)]
        return original_predict(self, features, **kwargs)

    monkeypatch.setattr(comparison, "create_estimator", small_estimator)
    monkeypatch.setattr(Pipeline, "fit", fit)
    monkeypatch.setattr(Pipeline, "predict_proba", predict)
    first = comparison.compare_models(data, DEFINITIONS, assignment, baseline, CONFIGS)
    second = comparison.compare_models(data, DEFINITIONS, assignment, baseline, CONFIGS)
    assert len(fitted) == 80
    pd.testing.assert_frame_equal(first.oof, second.oof)
    pd.testing.assert_frame_equal(data, original_data)
    pd.testing.assert_frame_equal(baseline, original_baseline)
    pd.testing.assert_frame_equal(first.assignments, assignment)
    pd.testing.assert_frame_equal(
        first.oof.loc[first.oof.model == "logistic_regression"].reset_index(drop=True),
        baseline.loc[baseline.model == "logistic_regression"].reset_index(drop=True),
    )
    assert first.oof.groupby(["feature_set", "model"]).size().eq(60).all()
    assert len(first.summary) == 12 and len(first.folds) == 60
    assert np.isfinite(first.oof.probability).all() and first.oof.probability.between(0, 1).all()
    report = build_report(first, {})
    assert all(name in report for name in REMOVED)
    assert all(name in report for name in comparison.ALL_MODELS)
    assert "ddof=1" in report
    assert len(comparison.comparison_deltas(first)) == 69


@pytest.mark.parametrize("damage", ["id", "target", "fold", "duplicate", "inf", "order"])
def test_corruption_stops_before_fit(damage: str, monkeypatch: pytest.MonkeyPatch) -> None:
    data, assignment, baseline = fixture()
    if damage == "id":
        baseline.loc[60, "EmployeeNumber"] = -1
    elif damage == "target":
        baseline.loc[60, "Attrition"] = 1 - baseline.loc[60, "Attrition"]
    elif damage == "fold":
        baseline.loc[60, "fold"] = 4
    elif damage == "duplicate":
        baseline.loc[61] = baseline.loc[60]
    elif damage == "inf":
        baseline.loc[60, "probability"] = np.inf
    else:
        assignment = assignment.iloc[::-1].reset_index(drop=True)

    def forbidden(*args: Any, **kwargs: Any) -> Any:
        raise AssertionError("Mismatch must stop before fitting")

    monkeypatch.setattr(Pipeline, "fit", forbidden)
    with pytest.raises(ValueError):
        comparison.compare_models(data, DEFINITIONS, assignment, baseline, CONFIGS)


def test_final_path_rejected_before_access(monkeypatch: pytest.MonkeyPatch) -> None:
    from scripts.compare_baselines_v2 import run

    def forbidden(*args: Any, **kwargs: Any) -> Any:
        raise AssertionError("No path inspection allowed")

    monkeypatch.setattr(Path, "is_symlink", forbidden)
    monkeypatch.setattr(Path, "open", forbidden)
    with pytest.raises(ValueError, match="Locked final test"):
        run(Path("data/processed/final_test_raw_v1.csv"))


def test_xgboost_missing_sentinel_is_json_safe() -> None:
    import json

    from scripts.compare_baselines_v2 import json_parameters

    parameters = create_estimator(CONFIGS["xgboost"]).get_params(deep=False)
    encoded = json.dumps(json_parameters(parameters), allow_nan=False)
    assert json.loads(encoded)["missing"] == "nan"
